version: '3.7'
services:
  container_orchestrator:
    build: .
    restart: on-failure
    ports:
      - 0.0.0.0:7655:7655/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
